local assert = require("tests.helpers.assert")
local CursorStore = require("tend.rpc.cursor_store")

describe("tend.rpc.cursor_store basics", function()
    it("returns 0 for an unknown stream", function()
        local store = CursorStore.new()
        assert.equal(store:get("ws", "session:s1"), 0)
    end)

    it("records and reads a cursor per (workspace, stream)", function()
        local store = CursorStore.new()
        store:record("ws", "session:s1", 5)
        store:record("ws", "session:s2", 9)
        store:record("ws2", "session:s1", 3)
        assert.equal(store:get("ws", "session:s1"), 5)
        assert.equal(store:get("ws", "session:s2"), 9)
        -- Same stream id under a different workspace is a distinct cursor.
        assert.equal(store:get("ws2", "session:s1"), 3)
    end)

    it("never moves a cursor backward via record", function()
        local store = CursorStore.new()
        store:record("ws", "s", 10)
        local kept = store:record("ws", "s", 4)
        assert.equal(kept, 10)
        assert.equal(store:get("ws", "s"), 10)
    end)

    it("reset sets a cursor explicitly, including backward", function()
        local store = CursorStore.new()
        store:record("ws", "s", 10)
        store:reset("ws", "s", 3)
        assert.equal(store:get("ws", "s"), 3)
    end)

    it("seen reports whether a seq is at or before the cursor", function()
        local store = CursorStore.new()
        store:record("ws", "s", 5)
        assert.is_true(store:seen("ws", "s", 5))
        assert.is_true(store:seen("ws", "s", 4))
        assert.is_false(store:seen("ws", "s", 6))
    end)

    it("forgets a single stream and a whole workspace", function()
        local store = CursorStore.new()
        store:record("ws", "a", 1)
        store:record("ws", "b", 2)
        store:forget("ws", "a")
        assert.equal(store:get("ws", "a"), 0)
        assert.equal(store:get("ws", "b"), 2)
        store:forget_workspace("ws")
        assert.equal(store:get("ws", "b"), 0)
    end)
end)

describe("tend.rpc.cursor_store epoch", function()
    it(
        "does not discard on the first epoch and keeps cursors within it",
        function()
            local store = CursorStore.new()
            local discarded = store:set_epoch("e1")
            assert.is_false(discarded)
            store:record("ws", "s", 7)
            -- Re-binding the same epoch keeps everything.
            assert.is_false(store:set_epoch("e1"))
            assert.equal(store:get("ws", "s"), 7)
        end
    )

    it("discards stale cursors when the epoch changes", function()
        local store = CursorStore.new()
        store:set_epoch("e1")
        store:record("ws", "s", 7)
        local discarded = store:set_epoch("e2")
        assert.is_true(discarded)
        assert.equal(store:get("ws", "s"), 0)
    end)
end)
